# Generated by Django 5.2 on 2025-05-06 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add category', max_length=200, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('i', 'income'), ('e', 'expense')], default='e', help_text='Transaction Status', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default_profile.png', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Add amount of money', max_digits=12, verbose_name='Amount of money')),
                ('title', models.CharField(help_text='Add transaction title', max_length=200)),
                ('date', models.DateTimeField(help_text='Add transaction date')),
                ('description', models.TextField(blank=True, help_text='Write description (optional)', max_length=2000)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_tracker_app.category')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_tracker_app.type')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Account balance')),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_tracker_app.profile')),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_tracker_app.transaction')),
            ],
        ),
    ]
