# Generated by Django 5.2 on 2025-05-06 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_tracker_app.profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_tracker_app.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('i', 'Income'), ('e', 'Expense')], default='e', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(help_text='Add transaction date'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
